### ISSUE TITLE
PhoenixMiner - unable to get fan speed - Unknown Error (999) - not counted?

### ISSUE THREAD

**Issue by borzaka** [Undertrey/ZcashMinerAutorun#10]
I believe this error is not counted. 
`unable to get fan speed - Unknown Error (999)`

```
2018.07.23:11:10:41.062: eths Eth: New job #e25417d1 from europe.ethash-hub.miningpoolhub.com:20535; diff: 4300MH
2018.07.23:11:10:41.209: main Eth speed: 265.566 MH/s, shares: 4559/0/9, time: 21:05
2018.07.23:11:10:41.209: main GPUs: 1: 55.620 MH/s (960/9) 2: 55.138 MH/s (936) 3: 55.181 MH/s (949) 4: 33.195 MH/s (610) 5: 33.186 MH/s (581) 6: 33.246 MH/s (523)
2018.07.23:11:10:42.908: hwmc GPU4: unable to get fan speed - Unknown Error (999)
2018.07.23:11:10:43.033: main GPU1: 57C 61%, GPU2: 59C 66%, GPU3: 57C 61%, GPU4: 53C, GPU5: 54C 56%, GPU6: 50C 50%
2018.07.23:11:10:46.284: main Eth speed: 265.675 MH/s, shares: 4559/0/9, time: 21:05
2018.07.23:11:10:46.284: main GPUs: 1: 55.621 MH/s (960/9) 2: 55.015 MH/s (936) 3: 55.153 MH/s (949) 4: 33.295 MH/s (610) 5: 33.285 MH/s (581) 6: 33.305 MH/s (523)
2018.07.23:11:10:48.042: eths Eth: Received: {"id":null,"method":"mining.notify","params":["4ef0","0x8e01b76c5582b4dc7767c826796e3686f76800a582969ee015467943b568544d","0x8308d376eeb469b7ff84bd59c51988d9618b208dc3b951d1dc1918fa08306723","0x00000000ffb34c02420e9948eacd78cf33b059a88ade1ff0614f7f3c303cf3a7",true]}
2018.07.23:11:10:48.042: eths Eth: New job #8e01b76c from europe.ethash-hub.miningpoolhub.com:20535; diff: 4300MH
2018.07.23:11:10:48.906: eths Eth: Send: {"id":6,"jsonrpc":"2.0","method":"eth_submitHashrate","params":["0xfc6afc8","0x147cd3249fdeace1c3c74eae574a2ef8b94672b90dc9a6eb740bd5f989c33bf6"]}
```

[Official answer by PhoenixMiner](https://bitcointalk.org/index.php?topic=2647654.msg29013730#msg29013730)

> This is an NVML (the Nvidia hardware monitoring library) internal error. We have seen similar errors on our GTX1060s. Additional symptoms include high CPU usage (either by the miner or the MSI Afterburner). The same problems were also observed with Claymore's miner on the same rig. The short term-solution is to restart the rig (not just the miner) but the only long-term solution is to lower the memory overclock a little. We have found that even 20-30 MHz lower memory clocks completely solve the problem. Or you can continue mining and ignore the errors but the high CPU usage can be a real PITA when trying to control the rig via VNC or TeamViewer.

In my case, Afterburner completely freezes, can't do anything with it, but the mining continues. Remote desktop works.

And yes, I tried more aggressive overclocks, but I wasn't saved to an Afterburner profile, so a restart would solve this problem for me, and a stable Afterburner profile is selected by FarmWatchBot.

**Comment by Undertrey** [comment]
Thx for reporting. Added.

**Comment by Undertrey** [comment]
I need to revert this function because this is not critical error and can be solved by user.
Some users with high overclock reported that they just ignored this error and mining as well.
