### ISSUE TITLE
How does last share timeout check works? It killed the process 30 minutes later?

### ISSUE THREAD

**Issue by borzaka** [Undertrey/ZcashMinerAutorun#15]
PhoenixMiner

What happened here?

`Phnxautorun.log`
```
[2018. 08. 01.][ 4:03:35] Long share timeout... 1/50.
[2018. 08. 01.][ 4:03:44] Miner restarting, please wait... Miner ran for *03:50:19*.
[2018. 08. 01.][ 4:30:52] Process PhoenixMiner.exe was successfully killed.
[2018. 08. 01.][ 4:31:32] log*.txt moved to Logs folder as miner_8.1_4.27.log
```
[miner_8.1_4.27.log](https://github.com/Undertrey/FarmWatchBot/files/2249303/miner_8.1_4.27.log)

I see ETH share found! during that time. For example:
`2018.08.01:04:03:17.231: GPU1 Eth: GPU1: ETH share found!`

I see my hashrate dropped that time, but that was because sometime miner restarted: `New month reached`
And this miner restart messed up my overclock settings. Only miner restart is not always working good for me. A reboot would be better. Any option for that? Instead restarting miner, restart PC in some cases.

**Comment by Undertrey** [comment]
Hello.

True - ETH share is found, but this option checking "share accepting", your miner can found 100500 shares but you earn moneys only for accepted ones. In case if 10 minutes or more your miner can't send a solution for share (accepter one) script will restart miner.

About every month restart miner is the best option. 

Thx for reporting!
