### ISSUE TITLE
Feature Request: Pause Mining between certain time of day

### ISSUE THREAD

**Issue by TonyVH316** [Undertrey/ZcashMinerAutorun#17]
Utility now forces me to be on tier. It is most expensive to mine from 5-8pm, would like ability to tell system to pause all mining activity to save power between specified time. thank

**Comment by Rakly3** [comment]
Assuming you're using windows, you can do that in the task scheduler.
Start task @8pm
Force Stop task @5am (probably 2 tasks to stop. Watchdog and miner)

Enable Windows Godmode to find it easily
https://www.cnet.com/how-to/activate-godmode-in-windows-10/

**Comment by Undertrey** [comment]
Hello. Or you can buy premium script version and use Telegram commands to manually pause / resume your Rig (Rigs).
