### ISSUE TITLE
Can’t start the bot

### ISSUE THREAD

**Issue by premiumheadshot** [Undertrey/ZcashMinerAutorun#19]
I am not sure how to properly translate this error into English, but essentially I configured the .ini and after trying to start the bot this comes up:

![image](https://user-images.githubusercontent.com/84374898/118611739-71bf5a80-b7bd-11eb-830b-0f84b1e7e155.png)

**Comment by Undertrey** [comment]
have no idea, read carufully instructions and try to setup it again.
