### ISSUE TITLE
Can you add a function - check whether the network is unobstructed, otherwise kill miner?

### ISSUE THREAD

**Issue by franocisgar** [Undertrey/ZcashMinerAutorun#20]
Because if my mining machine has a network error, it will crash and cannot be restarted by using remote software. Therefore,choose to kill the miner according to the network changes(can use the ping command to finish this?). After killed, can constantly detect whether the network is unobstructed through the ping command. If it is unobstructed, restart the miner.

**Comment by Undertrey** [comment]
Hello. Write me please on [Telegram](t.me/acrefawn).
