### ISSUE TITLE
Miner working OK." Do not worry. - how to get full information in the miner?

### ISSUE THREAD

**Issue by RealJohnSilver** [Undertrey/ZcashMinerAutorun#3]
Hello,

how to get full information in the miner?
I do not want to receive a "Miner working OK." Do not worry. " I want to see full statistics online.
this can be done?

Thanks!

![notful1l](https://user-images.githubusercontent.com/36985598/37491986-38a55120-28a8-11e8-9cfe-032df2e4c00d.jpg)

**Comment by Undertrey** [comment]
Unfortunately it is impossible using standard CMD.EXE to both display information on screen and write it in the .log file at the same time. The script will ONLY work if the information is written in the .log file, making "on screen" impossible.

**Comment by asumarokov** [comment]
Is this feature(problem) only for only Ethminer?

**Comment by Undertrey** [comment]
You can ask miner developer to add --logfile function.
