### ISSUE TITLE
Hashrate unit

### ISSUE THREAD

**Issue by Frunzl** [Undertrey/ZcashMinerAutorun#4]
Hi,

First, I find your bot very useful. Great work!

I have encountered an issue with the Hashrate calculation. Since I have very different GPUs, (1x 1080TI, 2 x 1080, 3 x 1070), their hashrates are also quite different. Now, ccminer reports everything below 10 MH/s as 9999 KH/s (why 10MH and not 1??? nobody knows...) and the 1070's are giving me something like 8000 KH/s, whereas the ti gets as high as 22 MH/s.

I think, you can see the problem, since with your script, the numbers are just added (KH + MH), giving me nonsensical values (funny in fact, since if the ti drops out, with only "22" MH, it will not be noticed at all :) ) and I cannot really make use of the awesome low hashrate detection function.

Is there a possibility to correct this? or is there a parameter for ccminer to fix the output unit maybe?

**Comment by Undertrey** [comment]
Hello. Thx. 10MH because 1000KH=1MH.

It is only possible to calculate all hashrate in KH. But it is so many different Ccminers and different cards so it is very hard to figure out exact value. Different .log syntax, etc... Im working on it. Thank you for reporting this issue.
