### ISSUE TITLE
Request: FarmWatchBot for z-enemy-1.09a miner

### ISSUE THREAD

**Issue by ikorzha** [Undertrey/ZcashMinerAutorun#5]
Hi, can you please update your script to support z-enemy-1.09a miner. (link to download below)
It has become a new hot miner X16S and X16R and LUX coins. 
Unfortunately there is currently nothing on the market to watch these script and restart it when it crashes.
I have to do it fairly often on my rig.  Please help!
You can download script here:
https://www.asylab.com/single-post/2018/05/10/Z-Enemy-miner-v109a-NVIDIA-for-Ravencoin-RVN-Pigeoncoin-PGN-Windows-Linux

**Comment by Undertrey** [comment]
Thank you

**Comment by ikorzha** [comment]
Hi thank you for adding support for Z-Enemy, I however do not see the watchdog  .bat file for download.
Can you please upload it please?

**Comment by Undertrey** [comment]
z-enemy it is ccminer fork. it always worked before but with some issues. Now all is fixed. You need to use Ccautorun.bat.

**Comment by ikorzha** [comment]
Never mind my previous post i do see it in readme now :)
THank you
