### ISSUE TITLE
phoenix miner hashrate report

### ISSUE THREAD

**Issue by terryxsq** [Undertrey/ZcashMinerAutorun#6]
Hi,

I have started using your script with phoenix miner. not sure if i am doing something wrong but when i enable telegram notifications it only says how long it is online and no hashrate information is sent to telegram.

**Comment by Undertrey** [comment]
Hello. Please try to enable everyhour reporting. Thank you!

**Comment by terryxsq** [comment]
hi , the hourly reporting is fine. it seems to be only an issue when there is only 1 gpu. i have several rigs it only happen to the rig with 1 gpu.

**Comment by Undertrey** [comment]
Please retest with latest version of script.
