### ISSUE TITLE
SRBMiner support

### ISSUE THREAD

**Issue by bellodox** [Undertrey/ZcashMinerAutorun#7]
Hello @Undertrey!
Very nice work indeed.. Many 10x for that.

Can I kindly ask you to provide support for SRBMiner as well? 
Thanks in advance for your time..

**Comment by Undertrey** [comment]
Hello. I need some logfiles and configured .bat file to start mining

**Comment by bellodox** [comment]
OK but can you explain more through what do you need exactly? :)

**Comment by Undertrey** [comment]
1) Logfile output using miner logfile option.
2) Configured .bat file for start mining using this miner
3) Logfiles with errors

I havent AMD gpus to test, only Nvidia.

**Comment by bellodox** [comment]
Not having AMD GPU wil be a problem then. Because it is AMD Cryptonight miner though..

**Comment by Undertrey** [comment]
Working on it...
