### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by whotheff** [Undertrey/ZcashMinerAutorun#8]
I have a firewall. When I run the eth_miner.exe after setup was done, It never connects. When I disable the firewall it connects, but the log is constantly spinning the cards with no work done. And for some strange reason it connects to ethermine.org only (it's the third option).

When i run clean bat file it connects to my pool instantly

**Comment by Undertrey** [comment]
Hello. I have some difficulties with eth miner (not claymores) searching for fix.
