### ISSUE TITLE
Time and date format inconsistency

### ISSUE THREAD

**Issue by borzaka** [Undertrey/ZcashMinerAutorun#9]
I really like your FarmWatchBot! Thank your for your work!

I just want to let you know, that the date and time format is different everywhere you use it.

Some examples:

- What time format is this?
![image](https://user-images.githubusercontent.com/1230402/43028313-759b0a1c-8c7f-11e8-8356-c51a2448aef9.png)
42,12?

- Logs folder:
```
miner_7.19_10.31.log
miner_7.20_0.18.log
miner_7.20_0.8.log
miner_7.20_22.33.log
```
I dont understand, what time was this? `miner_7.20_0.8.log`

- Current log filename:
`log20180720_223357.txt`
This is good, fully understandable. :)

- Screenshot folder:
`miner_7.20_0.18.jpg`

- Timestamps used in logs:
`2018.07.19:10:32:09.370`

I think the best format for the file names should look like this:
`log_20180720_223357.txt`
`screenshot_20180720_223357.jpg`
`miner_20180720_223357.txt`

**Comment by Undertrey** [comment]
Hello.

1) 0 hours 45 minutes 42 seconds 12 miliseconds (this all is current time)
2) 7 month 19 date 10 hour 31 minutes (same with 0.8 - means 0 hours and 8 min)

It is possible to change it but in generally it is problematic because of differend date/time formats in different countries. For me this format is more understandable and this all .log files is needed for me :)

**Comment by borzaka** [comment]
OK, I understand your point. But if you would use double digits for example, than the file orders would be in order. :) Check this:
```
miner_7.20_0.18.log
miner_7.20_0.8.log
```

In this case, the 0 hours and 18 minutes log file "before" than the 0 hours and 8 minutes.

With double digits it would like this and would be in order:
```
miner_7.20_00.08.log
miner_7.20_00.18.log
```

Other thing:
In the root, you name the logfile like this: `log20180729_185506`
than you rename it something like this: `miner_7.29_18.55`
Many information is lost: year, sec. So how about: `log20180729_185506` renaming to `miner_20180729_185506`?
It looks easier, and understandable.

I respect your choice, but it's not logical for me.

**Comment by Undertrey** [comment]
Root logfile name given by Phoenix miner. not my script. In batch programming language digits 00-09 are not a numbers. Will be syntax error.
